name: Build Kernel

on:
  workflow_call:
    inputs:
      include_ksu:
        required: true
        type: string
      kernel_git:
        required: true
        type: string
      kernel_branch:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build-kernel:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        id: build
        run: |
            echo "Building ${{ inputs.include_ksu }}"
            sudo bash main.sh ${{ inputs.include_ksu }} ${{ inputs.kernel_git }} ${{ inputs.kernel_branch }}
      - name: Prepqre Upload
        id: prepare
        run: |
          echo "name=$(cat "$GITHUB_WORKSPACE/out/name*")" >> $GITHUB_ENV
      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: out/artifacts/*.zip
      - name: Upload bodyFile
        uses: actions/upload-artifact@v4
        with:
          name: bodyFile-${{ env.name }}
          path: out/bodyFile.md
