name: Build Kernel

on:
  workflow_call:
    inputs:
      include_ksu:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Build
        id: build
        run: |
            echo "Building ${{ inputs.include_ksu }}"
            sudo bash main.sh | -s ${{ inputs.include_ksu }}
