name: CI Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Previous Tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0
      - name: New Tag
        id: newtag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Environment
        id: environment
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh
      - name: Build
        id: build
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash main.sh
          sudo chmod -R 0777 ./*
          echo "name=$(cat "$GITHUB_WORKSPACE/out/name.txt")" >> $GITHUB_ENV
          echo "filename=$(cat "$GITHUB_WORKSPACE/out/filename.txt")" >> $GITHUB_ENV
      - name: Release
        id: upload
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.name }}"
          #tag: ${{ steps.newtag.outputs.minor }}
          tag: ${{ steps.newtag.outputs.patch }}
          allowUpdates: false
          bodyFile: "${{ github.workspace }}/out/bodyFile.md"
          artifacts: "${{ github.workspace }}/out/${{ env.filename }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup
        id: cleanup
        run:  |
          rm ${{ github.workspace }}/out/*
