name: CI Build

on:
  workflow_dispatch:
    inputs:
      build_ksu:
        required: true
        type: boolean
      build_nonksu:
        required: true
        type: boolean
      build_manager:
        required: true
        type: boolean
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    
  build-ksu:
    uses: ./.github/workflows/build-kernel.yml
    with:
      include_ksu: true

  build-nonksu:
    uses: ./.github/workflows/build-kernel.yml
    with:
      include_ksu: false
      
  build:
    needs: [build-manager, build-ksu, build-nonksu]
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Environment
        id: environment
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh
          
      - name: Get Tag
        id: tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          if [[ -z "$latest_tag" ]]; then latest_tag='v0'; fi
          echo "Latest Tag: $latest_tag"
          echo "tag=v$((${latest_tag:1} + 1))" >> $GITHUB_ENV
          
      - name: Download manager
        id: manager
        uses: actions/download-artifact@v4
        with:
          name: manager
          path: .
          
      - name: Build
        id: build
        run: |
          cd $GITHUB_WORKSPACE
          sudo chmod -R 0777 ./*
          echo "name=$(cat "$GITHUB_WORKSPACE/out/name.txt")" >> $GITHUB_ENV
          echo "filename=$(cat "$GITHUB_WORKSPACE/out/filename.txt")" >> $GITHUB_ENV
          cp ./KernelSU*.apk ./out/artifacts/Manager.apk
          
      - name: Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.name }}"
          tag: "${{ env.tag }}"
          allowUpdates: false
          bodyFile: "${{ github.workspace }}/out/bodyFile.md"
          artifacts: "${{ github.workspace }}/out/artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup
        id: cleanup
        run: rm -r ${{ github.workspace }}/out/*
