name: CI Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Environment
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash env.sh
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash main.sh
          sudo chmod -R 0777 ./*
      - name: Release‌‌
        uses: ncipollo/release-action@main
        with:
          name: "${{ github.workspace }}/out/RELEASETITLE.txt"
          tag: "${{ github.workspace }}/out/TAG.txt"
          allowUpdates: false
          bodyFile: "${{ github.workspace }}/out/RELEASE.md"
          artifacts: "${{ github.workspace }}/out/*"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup
        run:  |
          rm ${{ github.workspace }}/out/*
